import { ContentList } from '../../content-list';
import { Block } from '../../type/block/block';
import { AirBlock } from '../../type/block/environment/air-block';
import { SpawnBlock } from '../../type/block/environment/spawn-block';
import { Cliff } from '../../type/block/environment/cliff';
import { Floor } from '../../type/block/environment/floor';
import { ShallowLiquid } from '../../type/block/environment/shallow-liquid';
import { StaticWall } from '../../type/block/environment/static-wall';
import { TreeBlock } from '../../type/block/environment/tree-block';
import { Prop } from '../../type/block/environment/prop';
import { DoubleOverlayFloor } from '../../type/block/environment/double-overlay-floor';
import { OverlayFloor } from '../../type/block/environment/overlay-floor';

export class BlocksEnvironment extends ContentList<Block> {
    air = new AirBlock('air');
    spawn = new SpawnBlock('spawn');
    cliff = new Cliff('cliff');
    deepwater = new Floor('deepwater');
    water = new Floor('water');
    taintedWater = new Floor('taintedWater');
    darksandTaintedWater = new ShallowLiquid('darksand-tainted-water');
    sandWater = new ShallowLiquid('sand-water');
    darksandWater = new ShallowLiquid('darksand-water');
    tar = new Floor('tar');
    slag = new Floor('slag');
    space = new Floor('space');
    stone = new Floor('stone');
    craters = new Floor('craters');
    char = new Floor('char');
    basalt = new Floor('basalt');
    hotrock = new Floor('hotrock');
    magmarock = new Floor('magmarock');
    sand = new Floor('sand');
    darksand = new Floor('darksand');
    dirt = new Floor('dirt');
    mud = new Floor('mud');
    dacite = new Floor('dacite');
    grass = new Floor('grass');
    salt = new Floor('salt');
    snow = new Floor('snow');
    ice = new Floor('ice');
    iceSnow = new Floor('ice-snow');
    shale = new Floor('shale');
    duneWall = new StaticWall('dune-wall');
    sandWall = new StaticWall('sand-wall');
    saltWall = new StaticWall('salt-wall');
    shrubs = new StaticWall('shrubs');
    shaleWall = new StaticWall('shale-wall');
    sporePine = new StaticWall('spore-pine');
    snowPine = new StaticWall('snow-pine');
    pine = new StaticWall('pine');
    whiteTreeDead = new TreeBlock('white-tree-dead');
    whiteTree = new TreeBlock('white-tree');
    sporeCluster = new Prop('sporec-cluster');
    boulder = new Prop('boulder');
    snowBoulder = new Prop('snow-boulder');
    shaleBoulder = new Prop('shale-boulder');
    sandBoulder = new Prop('shale-boulder');
    daciteBoulder = new Prop('dacite-boulder');
    basaltBoulder = new Prop('basalt-boulder');
    moss = new Floor('moss');
    sporeMoss = new Floor('spore-moss');
    metalFloor = new Floor('metal-floor');
    metalFloorDamaged = new Floor('metal-floor-damaged');
    metalFloor2 = new Floor('metal-floor-2');
    metalFloor3 = new Floor('metal-floor-3');
    metalFloor4 = new Floor('metal-floor-4');
    metalFloor5 = new Floor('metal-floor-5');
    darkPanel1 = new Floor('dark-panel-1');
    darkPanel2 = new Floor('dark-panel-2');
    darkPanel3 = new Floor('dark-panel-3');
    darkPanel4 = new Floor('dark-panel-4');
    darkPanel5 = new Floor('dark-panel-5');
    darkPanel6 = new Floor('dark-panel-6');
    darkMetal = new StaticWall('dark-metal');
    pebbles = new DoubleOverlayFloor('pebbles');
    tendrils = new OverlayFloor('tendrils');
    // TODO: Complete everything
}
